---
title: "Post Analysis"
author: "Shozen Dan"
date: "11/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
```

```{r message=FALSE}
df <- read_csv("../data/score.csv")
head(df)
```

```{r}
ggplot(df, aes(x=texture)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1, color = "grey30"
                 ) + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(1,4,0.5), limits = c(1,4))
```

```{r}
ggplot(df, aes(x=pores)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1, color = "grey30"
                 ) + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(1,4,0.5), limits = c(1,4))
```
```{r}
ggplot(df, aes(x=spot)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1, color = "grey30"
                 ) + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(1,4,0.5), limits = c(1,4))
```

```{r}
ggplot(df, aes(x=saggy)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1, color = "grey30"
                 ) + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(1,4,0.5), limits = c(1,4))
```
```{r}
ggplot(df, aes(x=clear)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1, color = "grey30"
                 ) + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(1,4,0.5), limits = c(1,4))
```

```{r}
ggplot(df, aes(x=melanin)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1, color = "grey30"
                 ) + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(1,4,0.5), limits = c(1,4))
```

```{r}
ggplot(df, aes(x=wrinkles)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.1, color = "grey30"
                 ) + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(1,4,0.5), limits = c(1,4))
```

```{r}
df <- df %>% mutate(total = texture + pores + spot + saggy + clear + melanin + wrinkles)

ggplot(df, aes(x = total)) + 
  geom_histogram(aes(y = ..density..),
                 binwidth = 0.5, color = "grey30"
                 ) + 
  geom_density(alpha = .2, fill = "antiquewhite3") + 
  scale_x_continuous(breaks = seq(9,29,2), limits = c(9,29))
```

```{r}
df %>% 
  filter(total > 27)
```

```{r}
library(fmsb)

best1 <- df %>% filter(name == "./monitor-images\\1077.jpg") %>% select(texture, pores, spot, saggy, clear, melanin, wrinkles)
best1 <- rbind(rep(4,7) , rep(1,7) , best1)

radarchart(
  best1,
  axistype = 1,
  
  pcol=rgb(0.2,0.5,0.5,0.9), 
  pfcol=rgb(0.2,0.5,0.5,0.5),
  plwd=4,
  
  cglcol="grey", 
  cglty=1, 
  axislabcol="grey", 
  caxislabels=seq(0,4,1), 
  cglwd=0.8,
  vlcex=0.8
)
```

```{r}
worst1 <- df %>% filter(name == "./monitor-images\\1125.jpg") %>% select(texture, pores, spot, saggy, clear, melanin, wrinkles)
worst1 <- rbind(rep(4,7) , rep(1,7) , worst1)

radarchart(
  worst1,
  axistype = 1,
  
  pcol=rgb(0.2,0.5,0.5,0.9), 
  pfcol=rgb(0.2,0.5,0.5,0.5),
  plwd=4,
  
  cglcol="grey", 
  cglty=1, 
  axislabcol="grey", 
  caxislabels=seq(0,4,1), 
  cglwd=0.8,
  vlcex=0.8
)
```


```{r}
mid1 <- df %>% filter(name == "./monitor-images\\1106.jpg") %>% select(texture, pores, spot, saggy, clear, melanin, wrinkles)
mid1 <- rbind(rep(4,7) , rep(1,7) , mid1)

radarchart(
  worst1,
  axistype = 1,
  
  pcol=rgb(0.2,0.5,0.5,0.9), 
  pfcol=rgb(0.2,0.5,0.5,0.5),
  plwd=4,
  
  cglcol="grey", 
  cglty=1, 
  axislabcol="grey", 
  caxislabels=seq(0,4,1), 
  cglwd=0.8,
  vlcex=0.8
)
```

